# Dockerfile.test
FROM python:3.11.8

WORKDIR /app

# Copy just the requirements file first to leverage Docker cache
COPY requirements.txt .

# Create and activate venv
RUN python -m venv venv
RUN /bin/bash -c "source venv/bin/activate"

# Install requirements
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Command to run tests
CMD ["pytest"]
