name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'
    
      - name: Validate Python formatting with black
        run: |
          python -m pip install --upgrade pip
          pip install black
          black --check .

  unit-tests:
    runs-on: ubuntu-latest
    needs: format-check

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image for testing
        run: docker build -t bluffball:test -f dockerfile.test .

      - name: Run tests in Docker container
        run: docker run bluffball:test