name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'
    
      - name: Validate Python formatting with black
        run: |
          python -m pip install --upgrade pip
          pip install black
          black --check .

  unit-tests:
    runs-on: ubuntu-latest
    needs: format-check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unit tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          coverage run -m pytest -vv
          coverage report
          coverage html
        
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage-html
        

      - name: Check test coverage
        run: coverage report --fail-under=95
